package storemanagerguiview;


import controller.Backend_DAO_db;
import javax.swing.JOptionPane;
import model.HardwareProduct;
import model.Product;
import model.SoftwareProduct;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author snoim
 */
public class AddNewProductForm extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProductForm
     */
    
    ManageCatalogForm _ManageCatalogForm;   
    
    public AddNewProductForm(ManageCatalogForm catalogForm) 
    {
        initComponents();
        _ManageCatalogForm = catalogForm;
        cbProductType.setSelectedIndex(0);
    }

    private AddNewProductForm() { }
    
    private boolean isInHardwareMode()
    {
        if (cbProductType.getSelectedItem().equals("Hardware"))
            return true;
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        text_3 = new javax.swing.JTextField();
        text_4 = new javax.swing.JTextField();
        text_1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblOtherField = new javax.swing.JLabel();
        text_2 = new javax.swing.JTextField();
        cbProductType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New product");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel2.setText("Product name:");

        jButton1.setBackground(new java.awt.Color(22, 147, 145));
        jButton1.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Add");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 0, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        text_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        text_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Float_only(evt);
            }
        });

        text_4.setToolTipText("");
        text_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        text_4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        text_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Numbers_only(evt);
            }
        });

        text_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel3.setText("Price per item:");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel4.setText("Product description:");

        lblOtherField.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        lblOtherField.setText("c");

        text_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        cbProductType.setBackground(new java.awt.Color(0, 153, 153));
        cbProductType.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        cbProductType.setForeground(new java.awt.Color(0, 153, 153));
        cbProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardware", "Software" }));
        cbProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOtherField)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProductType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(text_3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(text_4, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(text_2)))))
                .addGap(45, 45, 45))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {text_1, text_3, text_4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lblOtherField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(text_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(text_3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(text_4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {text_1, text_3, text_4});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cbProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductTypeActionPerformed
        if (isInHardwareMode())
            lblOtherField.setText("Warrenty Period:");
        else
            lblOtherField.setText("Number of Users:");
    }//GEN-LAST:event_cbProductTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try
      {
           Product newProduct = null;
           if (text_1.getText().isEmpty())
               throw new Exception("The name field is required");
           if (text_3.getText().isEmpty())
               throw new Exception("The Price field is required");
           if (text_4.getText().isEmpty())
           {
               if (isInHardwareMode())
                   throw new Exception("The Warrenty Period field is required");
               else
                   throw new Exception("The users field is required");
           }
           if (Integer.parseInt(text_4.getText()) <= -1)
           {
                if (isInHardwareMode())
                   throw new Exception("The Warrenty Period field is not valid");
               else
                   throw new Exception("The users field is not valid");
           }
           int random_int = (int)Math.floor(Math.random()*(9-0+1)+0);
           if (isInHardwareMode())
           {
               newProduct = new HardwareProduct();
               newProduct.setID(random_int + (int)Math.floor(Math.random()*(9-0+1)+0) + (int)Math.floor(Math.random()*(9-0+1)+0));
               newProduct.setName(text_1.getText());
               newProduct.setDescription(text_2.getText());
               newProduct.setPricePerUnit(Float.parseFloat(text_3.getText()));
               ((HardwareProduct)newProduct).setWarrantyPeriod(Integer.parseInt(text_4.getText()));
           }
           else
           {
               newProduct = new SoftwareProduct();
               newProduct.setID(random_int + (int)Math.floor(Math.random()*(9-0+1)+0) + (int)Math.floor(Math.random()*(9-0+1)+0));
               newProduct.setName(text_1.getText());
               newProduct.setDescription(text_2.getText());
               newProduct.setPricePerUnit(Float.parseFloat(text_3.getText()));
               ((SoftwareProduct)newProduct).setNumberOfUsers(Integer.parseInt(text_4.getText()));
           }      
            Backend_DAO_db.Get_singleton().AddProduct(newProduct);
            _ManageCatalogForm.RefreshProductList();
           JOptionPane.showMessageDialog(AddNewProductForm.this, "Product was successfully added");
      }
      catch (Exception ex)
      { JOptionPane.showMessageDialog(AddNewProductForm.this, ex.getMessage()); }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Numbers_only(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Numbers_only
         if(!Character.isDigit(evt.getKeyChar()))
                    evt.consume();      
    }//GEN-LAST:event_Numbers_only

    private void Float_only(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Float_only
        if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.' )
                    evt.consume();      
    }//GEN-LAST:event_Float_only

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddNewProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddNewProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddNewProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddNewProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddNewProductForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbProductType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblOtherField;
    private javax.swing.JTextField text_1;
    private javax.swing.JTextField text_2;
    private javax.swing.JTextField text_3;
    private javax.swing.JTextField text_4;
    // End of variables declaration//GEN-END:variables
}
